[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pydrever"
version = "24.1.1"
authors = [
  { name="Pieter van Geer", email="pieter.vangeer@deltares.com" },
]
description = "Tools that facilitate analysis of dike safety against flooding."
# readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU GENERAL PUBLIC LICENSE Version 3",
    "Operating System :: Windows",
]

dependencies = [
"numpy",
"matplotlib",
"pythonnet"
]

[project.urls]
Homepage = "https://github.com/pvangeer/dikerosion-python"
Issues = "https://github.com/pvangeer/dikerosion-python/issues"

[tool.setuptools.package-data]
"*" = ["*.dll"]
