# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest-xlarge]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Instal MacPorts
      if: ${{ matrix.os == 'macos-latest-xlarge' }} 
      uses: melusina-org/setup-macports@v1
      id: 'macports'
    - name: Install mono
      if: ${{ matrix.os == 'macos-latest-xlarge' }} 
      run: |
        export PATH=$PATH:/opt/local/bin
        sudo port install mono
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Test with pytest
      run: |
        pytest -v
